### ISSUE TITLE
CloudFront invalidations don't work if the distribution was reconfigured

### ISSUE THREAD

**Issue by JJC1138** [JJC1138/staticwebsync#15]

**Comment by JJC1138** [comment]
invalidating cached copies of changed or deleted files
Traceback (most recent call last):
  File "/Users/Jon/bin/sws", line 11, in <module>
    sys.exit(main())
  File "/Users/Jon/Work/py3env/lib/python3.5/site-packages/staticwebsync/sws.py", line 105, in main
    staticwebsync.setup(args)
  File "/Users/Jon/Work/py3env/lib/python3.5/site-packages/staticwebsync/__init__.py", line 546, in setup
    invalidate_all(paths)
  File "/Users/Jon/Work/py3env/lib/python3.5/site-packages/staticwebsync/__init__.py", line 521, in invalidate_all
    cf.create_invalidation(DistributionId=distribution['Id'], InvalidationBatch=batch)
KeyError: 'Id'
